/**
 * js/apotek/etalase.js
 * Etalase Haypop: master produk, bundling transaksi, dan laporan terpisah.
 * Aturan: nilai Etalase tidak masuk totalAkhir/HPP/stok/payroll/keuangan utama.
 */
(function () {
    var VERSION = 'etalase-v3-separate-ledger';
    window.AppApotekEtalase = window.AppApotekEtalase || {};
    var E = window.AppApotekEtalase;
    E.produk = E.produk || [];
    E.sales = E.sales || [];
    E.transaksiProduk = E.transaksiProduk || [];
    E.bulan = (window.Utils && Utils.thisMonth) ? Utils.thisMonth() : new Date().toISOString().slice(0,7);
    E.unsubProduk = null; E.unsubSales = null; E.unsubTransaksiProduk = null;

    function money(n){ return Number(n)||0; }
    function fmt(n){ return Utils.formatRupiah(money(n)); }
    function products(){ return (E.transaksiProduk||[]).filter(function(p){ return p.aktif!==false && money(p.harga)>0; }); }
    function selection(){
        var out=[];
        document.querySelectorAll('[data-etalase-row]').forEach(function(row){
            var sel=row.querySelector('[data-etalase-product]'), qtyEl=row.querySelector('[data-etalase-qty]');
            if(!sel || !sel.value) return;
            var p=products().find(function(x){return x.id===sel.value;}); if(!p) return;
            var qty=Math.max(1,parseInt(qtyEl&&qtyEl.value,10)||1);
            out.push({produkId:p.id,namaProduk:p.nama||'-',harga:money(p.harga),qty:qty,subtotal:money(p.harga)*qty});
        });
        return out;
    }
    function etalaseTotal(){ return selection().reduce(function(s,x){return s+x.subtotal;},0); }

    E.render=function(){
        return '<div class="page-enter max-w-6xl space-y-4"><div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h2 class="text-xl font-bold text-gray-800 dark:text-white">Etalase Haypop</h2><p class="text-sm text-slate-500 dark:text-slate-400">Produk bundling dan penjualannya dicatat terpisah dari keuangan apotek.</p></div><button onclick="AppApotekEtalase.bukaFormProduk()" class="px-4 py-2 rounded-xl bg-primary-600 text-white text-sm font-bold flex items-center gap-2"><i data-lucide="plus" class="w-4 h-4"></i> Produk Etalase</button></div><div id="etalase-content"><div class="flex justify-center py-16"><div class="spinner"></div></div></div></div>';
    };
    E.init=function(){ if((window.currentRole||'')!=='keuangan') return; E.listenProduk(); E.listenSales(); };
    E.destroy=function(){ if(E.unsubProduk)E.unsubProduk(); if(E.unsubSales)E.unsubSales(); if(E.unsubTransaksiProduk)E.unsubTransaksiProduk(); E.unsubProduk=E.unsubSales=E.unsubTransaksiProduk=null; };
    E.listenProduk=function(){ if(E.unsubProduk)E.unsubProduk(); E.unsubProduk=db.collection('etalaseProduk').onSnapshot(function(s){E.produk=[];s.forEach(function(d){var x=d.data();x.id=d.id;E.produk.push(x);});E.produk.sort(function(a,b){return String(a.nama||'').localeCompare(String(b.nama||''));});E.renderView();},function(e){Utils.toast('Gagal memuat produk Etalase: '+e.message,'error');}); };
    E.listenSales=function(){ if(E.unsubSales)E.unsubSales(); var p=E.bulan.split('-'), last=new Date(parseInt(p[0],10),parseInt(p[1],10),0).getDate(); E.unsubSales=db.collection('etalasePenjualan').where('tanggal','>=',E.bulan+'-01').where('tanggal','<=',E.bulan+'-'+String(last).padStart(2,'0')).orderBy('tanggal','desc').onSnapshot(function(s){E.sales=[];s.forEach(function(d){var x=d.data();x.id=d.id;E.sales.push(x);});E.renderView();},function(e){Utils.toast('Gagal memuat penjualan Etalase: '+e.message,'error');}); };
    function syncTransactionProductOptions(){ var active=products(),valid={};active.forEach(function(p){valid[p.id]=p;});document.querySelectorAll('[data-etalase-product]').forEach(function(sel){var current=sel.value,options='<option value="">-- Pilih Produk --</option>';active.forEach(function(p){options+='<option value="'+Utils.escapeHtml(p.id)+'">'+Utils.escapeHtml(p.nama)+' — '+fmt(p.harga)+'</option>';});sel.innerHTML=options;sel.disabled=!active.length;if(current&&valid[current])sel.value=current;else sel.value='';});var add=document.getElementById('trx-etalase-add');if(add){add.disabled=!active.length;add.classList.toggle('opacity-50',!active.length);add.classList.toggle('cursor-not-allowed',!active.length);}if(!active.length){var toggle=document.getElementById('trx-etalase-toggle');if(toggle&&toggle.checked){toggle.checked=false;var list=document.getElementById('trx-etalase-items');if(list){list.innerHTML='';list.classList.add('hidden');}}}if(document.getElementById('trx-etalase-box'))E.refreshTransaksiTotal(); }
    E.listenTransaksiProduk=function(){ if(E.unsubTransaksiProduk)E.unsubTransaksiProduk(); E.unsubTransaksiProduk=db.collection('etalaseProduk').where('aktif','==',true).onSnapshot(function(s){E.transaksiProduk=[];s.forEach(function(d){var x=d.data();x.id=d.id;E.transaksiProduk.push(x);});E.transaksiProduk.sort(function(a,b){return String(a.nama||'').localeCompare(String(b.nama||''));});syncTransactionProductOptions();},function(e){console.warn('Etalase products:',e);}); };
    E.ubahBulan=function(v){E.bulan=v||E.bulan;E.listenSales();};
    E.renderView=function(){
        var c=document.getElementById('etalase-content'); if(!c)return; var total=0,qty=0,by={};
        E.sales.forEach(function(s){(s.items||[]).forEach(function(i){var q=money(i.qty),sub=money(i.subtotal);qty+=q;total+=sub;by[i.produkId]=by[i.produkId]||{nama:i.namaProduk||'-',qty:0,total:0};by[i.produkId].qty+=q;by[i.produkId].total+=sub;});});
        var h='<div class="space-y-4"><div class="grid grid-cols-1 sm:grid-cols-3 gap-4"><div class="bg-white dark:bg-slate-800 border rounded-xl p-4"><div class="text-xs text-slate-400">Periode</div><div class="font-bold mt-1">'+Utils.escapeHtml(E.bulan)+'</div></div><div class="bg-white dark:bg-slate-800 border rounded-xl p-4"><div class="text-xs text-slate-400">Qty Terjual</div><div class="text-xl font-black mt-1">'+qty+'</div></div><div class="bg-white dark:bg-slate-800 border rounded-xl p-4"><div class="text-xs text-slate-400">Total Penjualan Etalase</div><div class="text-xl font-black text-emerald-600 mt-1">'+fmt(total)+'</div></div></div>';
        h+='<div class="bg-white dark:bg-slate-800 border rounded-xl p-4"><label class="text-xs font-semibold text-slate-500">Bulan Penjualan</label><input type="month" value="'+E.bulan+'" onchange="AppApotekEtalase.ubahBulan(this.value)" class="block mt-1 px-3 py-2 rounded-lg border dark:bg-slate-900"></div>';
        h+='<div class="grid grid-cols-1 lg:grid-cols-2 gap-4"><div class="bg-white dark:bg-slate-800 border rounded-xl p-4"><div class="flex justify-between mb-3"><h3 class="font-bold">Produk & Harga</h3><span class="text-xs text-slate-400">Keuangan</span></div>'; if(!E.produk.length)h+='<p class="text-sm text-slate-400 py-6 text-center">Belum ada produk Etalase.</p>'; E.produk.forEach(function(p){h+='<div class="flex items-center justify-between gap-3 py-3 border-b last:border-0"><div><div class="font-semibold text-sm">'+Utils.escapeHtml(p.nama)+'</div><div class="text-xs text-slate-400">'+(p.aktif!==false?'Aktif':'Nonaktif')+'</div></div><div class="flex items-center gap-3"><b class="text-emerald-600">'+fmt(p.harga)+'</b><button onclick="AppApotekEtalase.bukaFormProduk(\''+p.id+'\')" class="text-xs text-primary-600 font-bold">Edit</button></div></div>';});
        h+='</div><div class="bg-white dark:bg-slate-800 border rounded-xl p-4"><h3 class="font-bold mb-3">Ringkasan Penjualan</h3>'; Object.keys(by).forEach(function(k){var x=by[k];h+='<div class="flex justify-between py-2 border-b last:border-0 text-sm"><span>'+Utils.escapeHtml(x.nama)+' × '+x.qty+'</span><b>'+fmt(x.total)+'</b></div>';}); if(!Object.keys(by).length)h+='<p class="text-sm text-slate-400 py-6 text-center">Belum ada penjualan Etalase.</p>'; h+='</div></div><div class="bg-sky-50 dark:bg-sky-900/20 border border-sky-100 dark:border-sky-800 rounded-xl p-4 text-xs text-sky-700 dark:text-sky-300">Penjualan Etalase dicatat terpisah. Tidak masuk jurnal pendapatan, HPP/persediaan, atau payroll.</div></div>';
        c.innerHTML=h;if(window.lucide)lucide.createIcons();
    };
    E.bukaFormProduk=function(id){ var p=id?E.produk.find(function(x){return x.id===id;}):null; var h='<div class="p-6 space-y-4"><div class="flex justify-between"><h3 class="font-bold text-lg">'+(p?'Edit Produk Etalase':'Produk Etalase Baru')+'</h3><button onclick="Utils.closeModal()"><i data-lucide="x" class="w-5 h-5"></i></button></div><div><label class="text-xs font-semibold">Nama Produk</label><input id="etalase-nama" value="'+Utils.escapeHtml(p?p.nama:'')+'" class="w-full mt-1 px-3 py-2 border rounded-lg"></div><div><label class="text-xs font-semibold">Harga Jual Bundling</label><input id="etalase-harga" type="number" min="0" value="'+(p?p.harga:'')+'" class="w-full mt-1 px-3 py-2 border rounded-lg"></div><label class="flex items-center gap-2 text-sm"><input id="etalase-aktif" type="checkbox" '+((!p||p.aktif!==false)?'checked':'')+'> Aktif di transaksi</label><div class="flex justify-end gap-2"><button onclick="Utils.closeModal()" class="px-4 py-2 rounded-lg bg-slate-100">Batal</button><button onclick="AppApotekEtalase.simpanProduk(\''+(id||'')+'\')" class="px-4 py-2 rounded-lg bg-primary-600 text-white font-bold">Simpan</button></div></div>'; Utils.openModal(h);if(window.lucide)lucide.createIcons(); };
    E.simpanProduk=function(id){ var nama=(document.getElementById('etalase-nama').value||'').trim(),harga=money(document.getElementById('etalase-harga').value),aktif=!!document.getElementById('etalase-aktif').checked; if(!nama)return Utils.toast('Nama produk wajib diisi.','error');if(harga<=0)return Utils.toast('Harga harus lebih dari 0.','error'); var data={nama:nama,harga:harga,aktif:aktif,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedByUid:(auth.currentUser&&auth.currentUser.uid)||''}; var op=id?db.collection('etalaseProduk').doc(id).update(data):db.collection('etalaseProduk').add(Object.assign(data,{createdAt:firebase.firestore.FieldValue.serverTimestamp()})); op.then(function(){Utils.closeModal();Utils.toast('Produk Etalase tersimpan.','success');}).catch(function(e){Utils.toast('Gagal menyimpan: '+e.message,'error');}); };

    function removeLegacyBoxes(){ var content=document.getElementById('trx-content');if(!content)return; Array.prototype.slice.call(content.querySelectorAll('*')).forEach(function(el){var txt=(el.textContent||'').trim();if(txt==='Tambahan Etalase'){var target=el.closest('[data-etalase-legacy], .border.rounded-xl, .rounded-xl.border');if(target&&target.id!=='trx-etalase-box')target.remove();}}); }
    function injectUI(){ var content=document.getElementById('trx-content');if(!content)return;removeLegacyBoxes();if(document.getElementById('trx-etalase-box'))return;var box=document.createElement('div');box.id='trx-etalase-box';box.setAttribute('data-etalase-version',VERSION);box.className='bg-white dark:bg-slate-800 rounded-xl border border-amber-200 dark:border-amber-800 p-5 mb-4';box.innerHTML='<div class="flex items-center justify-between gap-3 mb-3"><div><h3 class="font-semibold text-gray-800 dark:text-white">Etalase Haypop</h3><p class="text-xs text-slate-500">Opsional — pilih jika konsumen meminta bundling.</p></div><label class="flex items-center gap-2 text-sm font-semibold cursor-pointer"><input id="trx-etalase-toggle" type="checkbox" class="w-4 h-4" onchange="AppApotekEtalase.toggleTransaksi(this.checked)"> Tambahkan Etalase</label></div><div id="trx-etalase-items" class="hidden space-y-2"></div><button id="trx-etalase-add" type="button" class="hidden mt-3 text-sm font-semibold text-primary-600" onclick="AppApotekEtalase.tambahBarisTransaksi()">+ Tambah produk Etalase</button>';var totalBox=content.querySelector('#trx-grand-total'),totalCard=totalBox?totalBox.closest('.bg-white'):null;if(totalCard&&totalCard.parentElement)totalCard.parentElement.insertBefore(box,totalCard);else content.appendChild(box); }
    function addRow(){ var list=document.getElementById('trx-etalase-items');if(!list)return;if(!products().length){Utils.toast('Tidak ada produk Etalase yang aktif.','info');return;}var row=document.createElement('div');row.setAttribute('data-etalase-row','1');row.className='grid grid-cols-1 sm:grid-cols-[1fr_110px_130px_36px] gap-2 items-center';var options='<option value="">-- Pilih Produk --</option>';products().forEach(function(p){options+='<option value="'+Utils.escapeHtml(p.id)+'">'+Utils.escapeHtml(p.nama)+' — '+fmt(p.harga)+'</option>';});row.innerHTML='<select data-etalase-product class="w-full px-3 py-2 border rounded-lg text-sm dark:bg-slate-700 dark:text-white" onchange="AppApotekEtalase.refreshTransaksiTotal()">'+options+'</select><input data-etalase-qty type="number" min="1" value="1" class="w-full px-3 py-2 border rounded-lg text-sm text-center dark:bg-slate-700 dark:text-white" oninput="AppApotekEtalase.refreshTransaksiTotal()"><div data-etalase-subtotal class="px-3 py-2 bg-slate-50 dark:bg-slate-900 rounded-lg text-sm font-semibold text-right">Rp 0</div><button type="button" class="p-2 text-red-500" onclick="this.closest(\'[data-etalase-row]\').remove();AppApotekEtalase.refreshTransaksiTotal()"><i data-lucide="x" class="w-4 h-4"></i></button>';list.appendChild(row);if(window.lucide)lucide.createIcons({nodes:[row]}); }
    E.toggleTransaksi=function(checked){var list=document.getElementById('trx-etalase-items'),add=document.getElementById('trx-etalase-add');if(checked){if(list){list.classList.remove('hidden');if(!list.children.length)addRow();}if(add)add.classList.remove('hidden');}else{if(list){list.innerHTML='';list.classList.add('hidden');}if(add)add.classList.add('hidden');}E.refreshTransaksiTotal();};
    E.tambahBarisTransaksi=addRow; E.refreshTransaksiTotal=function(){var app=window.AppApotekTransaksi;if(app&&typeof app.hitungTotal==='function')app.hitungTotal();};

    function patchTransaction(){ if(!window.AppApotekTransaksi||window.AppApotekTransaksi.__etalasePatched===VERSION)return; var app=window.AppApotekTransaksi,origRender=app.renderForm,origTotal=app.hitungTotal,origReceipt=app.cetakStruk;app.__etalasePatched=VERSION;app.renderForm=function(){var r=origRender.apply(this,arguments);setTimeout(injectUI,0);return r;};app.hitungTotal=function(){var r=origTotal.apply(this,arguments),grand=document.getElementById('trx-grand-total');if(!grand)return r;var base=money(String(grand.textContent||'').replace(/[^0-9-]/g,'')),toggle=document.getElementById('trx-etalase-toggle'),add=toggle&&toggle.checked?etalaseTotal():0;document.querySelectorAll('[data-etalase-row]').forEach(function(row){var sel=row.querySelector('[data-etalase-product]'),qty=row.querySelector('[data-etalase-qty]'),sub=row.querySelector('[data-etalase-subtotal]'),p=sel&&products().find(function(x){return x.id===sel.value;});if(sub)sub.textContent=p?fmt(money(p.harga)*(Math.max(1,parseInt(qty&&qty.value,10)||1))):'Rp 0';});grand.textContent=fmt(base+add);return r;};app.cetakStruk=function(data,w){var items=selection(),add=items.reduce(function(s,x){return s+x.subtotal;},0),receipt=Object.assign({},data);if(items.length){receipt.etalaseItems=items;receipt.etalaseTotal=add;receipt.totalBayarKonsumen=money(data.totalAkhir)+add;}var result=origReceipt.call(this,receipt,w);if(items.length&&data&&data.id){db.collection('etalasePenjualan').doc(data.id).set({transaksiId:data.id,tanggal:data.tanggal||Utils.today(),items:items,total:add,totalApotek:money(data.totalAkhir),totalBayarKonsumen:money(data.totalAkhir)+add,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdByUid:(auth.currentUser&&auth.currentUser.uid)||''},{merge:true}).then(function(){Utils.toast('Penjualan Etalase tercatat terpisah dari keuangan.','success');}).catch(function(e){console.error('Gagal mencatat Penjualan Etalase:',e);Utils.toast('Transaksi apotek berhasil, tetapi pencatatan Etalase gagal: '+e.message,'error');});}return result;};E.listenTransaksiProduk(); }

    function cleanupDashboardLegacy(){ var c=document.getElementById('dashboard-content');if(!c)return;Array.prototype.slice.call(c.querySelectorAll('[data-etalase-dashboard-card], .etalase-dashboard-legacy')).forEach(function(x){x.remove();});Array.prototype.slice.call(c.querySelectorAll('*')).forEach(function(el){if((el.textContent||'').trim()==='Etalase Haypop Hari Ini'){var t=el.closest('.border.rounded-xl');if(t&&!t.hasAttribute('data-etalase-dashboard-card'))t.remove();}}); }
    function addDashboardCard(role){ var c=document.getElementById('dashboard-content');if(!c)return;cleanupDashboardLegacy();if(c.querySelector('[data-etalase-dashboard-card]'))return;var grid=c.querySelector('.grid');if(!grid)return;var card=document.createElement('div');card.setAttribute('data-etalase-dashboard-card','1');card.className='bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-5 shadow-sm flex items-center gap-4 min-w-0 flex-1';card.innerHTML='<div class="w-12 h-12 rounded-full bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center flex-shrink-0"><i data-lucide="store" class="w-6 h-6 text-amber-600 dark:text-amber-400"></i></div><div class="min-w-0 flex-1"><p class="text-xs text-slate-500 dark:text-slate-400 uppercase font-semibold truncate">Penjualan Etalase</p><h3 id="etalase-dashboard-value" class="text-lg sm:text-xl font-bold text-gray-800 dark:text-white truncate">Memuat...</h3><p id="etalase-dashboard-desc" class="text-[10px] text-slate-400 mt-1 truncate">Terpisah dari omzet apotek</p></div>';grid.appendChild(card);if(window.lucide)lucide.createIcons();var today=Utils.today(),start=role==='apotek'?today:today.slice(0,8)+'01',end=today;db.collection('etalasePenjualan').where('tanggal','>=',start).where('tanggal','<=',end).get().then(function(s){var total=0,qty=0;s.forEach(function(d){var x=d.data();total+=money(x.total);(x.items||[]).forEach(function(i){qty+=money(i.qty);});});var v=document.getElementById('etalase-dashboard-value'),d=document.getElementById('etalase-dashboard-desc');if(v)v.textContent=fmt(total);if(d)d.textContent=(role==='apotek'?'Hari ini · '+qty+' produk terjual':'Bulan ini · '+qty+' produk terjual')+' · tidak masuk omzet apotek';}).catch(function(e){var v=document.getElementById('etalase-dashboard-value');if(v)v.textContent='-';console.warn('Dashboard Etalase:',e);}); }
    function patchDashboard(){ if(!window.AppDashboard||window.AppDashboard.__etalasePatched===VERSION)return;var D=window.AppDashboard;D.__etalasePatched=VERSION;['renderApotek','renderKeuangan'].forEach(function(name){var orig=D[name];if(typeof orig!=='function')return;D[name]=function(){var r=orig.apply(this,arguments),tries=0;function wait(){tries++;if(document.getElementById('dashboard-content')&&document.getElementById('dashboard-content').querySelector('.grid'))addDashboardCard(name==='renderApotek'?'apotek':'keuangan');else if(tries<30)setTimeout(wait,200);}setTimeout(wait,100);return r;};}); }
    function boot(){patchTransaction();patchDashboard();}
    var timer=setInterval(function(){boot();if(window.AppApotekTransaksi&&window.AppDashboard)clearInterval(timer);},500);boot();
})();
